common: &common
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  host: 127.0.0.1

development:
  database: test-client_development
  <<: *common

test:
  database: test-client_test
  <<: *common
